# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands: # no build specification needed
      # - echo Build started on `date`
      # - echo Compiling the dist folder
      # - npm run-script build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - index.js
    - config.js
    - aws-client.js
    - secret.js
    - node_modules/**/*